### ISSUE TITLE
Build fails because of test failure in sonic-xcvrd/tests/test_xcvrd.py:test_SfpStateUpdateTask_task_run_stop()

### ISSUE THREAD

**Issue by patilshashidhar** [sonic-net/sonic-platform-daemons#370]
This failure happens once in three builds. It is not consistent and may be a timing issue.

=================================== FAILURES ===================================
____________ TestXcvrdScript.test_SfpStateUpdateTask_task_run_stop _____________

self = <tests.test_xcvrd.TestXcvrdScript object at 0x7fbd2e6508b0>

    @patch('xcvrd.xcvrd_utilities.port_mapping.subscribe_port_config_change', MagicMock(return_value=(None, None)))
    def test_SfpStateUpdateTask_task_run_stop(self):
        port_mapping = PortMapping()
        retry_eeprom_set = set()
        stop_event = threading.Event()
        sfp_error_event = threading.Event()
        task = SfpStateUpdateTask(DEFAULT_NAMESPACE, port_mapping, retry_eeprom_set, stop_event, sfp_error_event)
        task.start()
>       assert wait_until(5, 1, task.is_alive)
E       assert False
E        +  where False = wait_until(5, 1, <bound method Thread.is_alive of <SfpStateUpdateTask(SfpStateUpdateTask, stopped 140450521253632)>>)
E        +    where <bound method Thread.is_alive of <SfpStateUpdateTask(SfpStateUpdateTask, stopped 140450521253632)>> = <SfpStateUpdateTask(SfpStateUpdateTask, stopped 140450521253632)>.is_alive

tests/test_xcvrd.py:1039: AssertionError
=============================== warnings summary ===============================
/usr/lib/python3/dist-packages/_pytest/junitxml.py:446
  /usr/lib/python3/dist-packages/_pytest/junitxml.py:446: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0. See:
    https://docs.pytest.org/en/stable/deprecations.html#junit-family-default-value-change-to-xunit2
  for more information.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated xml file: /sonic/src/sonic-platform-daemons/sonic-xcvrd/test-results.xml -

----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name                                         Stmts   Miss  Cover
----------------------------------------------------------------
xcvrd/__init__.py                                0      0   100%
xcvrd/xcvrd.py                                1544    341    78%
xcvrd/xcvrd_utilities/__init__.py                0      0   100%
xcvrd/xcvrd_utilities/port_mapping.py          191     26    86%
xcvrd/xcvrd_utilities/sfp_status_helper.py      25      1    96%
----------------------------------------------------------------
TOTAL                                         1760    368    79%

Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
FAILED tests/test_xcvrd.py::TestXcvrdScript::test_SfpStateUpdateTask_task_run_stop
=================== 1 failed, 69 passed, 1 warning in 16.38s ===================
[  FAIL LOG END  ] [ target/python-wheels/bullseye/sonic_xcvrd-1.0-py3-none-any.whl ]
make: *** [slave.mk:878: target/python-wheels/bullseye/sonic_xcvrd-1.0-py3-none-any.whl] Error 1

**Comment by prgeor** [comment]
@mihirpat1 can you check this failure

**Comment by mihirpat1** [comment]
> @mihirpat1 can you check this failure

Sure @prgeor.
